import = ["/Users/lijialin/.config/alacritty/gruvbox-material.toml"]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font" }
glyph_offset = { x = 0, y = 3 }
offset = { x = 0, y = 6 }


[window]
decorations = "buttonless"
opacity = 0.94
padding = { x = 10, y = 10 }
blur = false

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  # tmux
  { chars = "\u0002c", key = "T", mods = "Command" },
  { chars = "\u0002x", key = "W", mods = "Command" },
  { chars = "\u0002%", key = "D", mods = "Command" },
  { chars = "\u0002\"", key = "D", mods = "Command|Shift" },
  { chars = "\u0002u", key = "U", mods = "Command" },
  { chars = "\u0002[", key = "LBracket", mods = "Command" },
  { chars = "\u0002]", key = "RBracket", mods = "Command" },
  { chars = "\u00021", key = "Key1", mods = "Command" },
  { chars = "\u00022", key = "Key2", mods = "Command" },
  { chars = "\u00023", key = "Key3", mods = "Command" },
  { chars = "\u00024", key = "Key4", mods = "Command" },
  { chars = "\u00025", key = "Key5", mods = "Command" },
  { chars = "\u00026", key = "Key6", mods = "Command" },
  { chars = "\u00027", key = "Key7", mods = "Command" },
  { chars = "\u00028", key = "Key8", mods = "Command" },
  { chars = "\u00029", key = "Key9", mods = "Command" },

  # zellij
  # { chars = "\u0002c", key = "T", mods = "Command" },
  # { chars = "\u0002x", key = "W", mods = "Command" },
  # { chars = "\u0002%", key = "D", mods = "Command" },
  # { chars = "\u0002\"", key = "D", mods = "Command|Shift" },
  # { chars = "\u0002u", key = "U", mods = "Command" },
  # { chars = "\u0002[", key = "LBracket", mods = "Command" },
  # { chars = "\u0002]", key = "RBracket", mods = "Command" },
  # { chars = "\u00021", key = "Key1", mods = "Command" },
  # { chars = "\u00022", key = "Key2", mods = "Command" },
  # { chars = "\u00023", key = "Key3", mods = "Command" },
  # { chars = "\u00024", key = "Key4", mods = "Command" },
  # { chars = "\u00025", key = "Key5", mods = "Command" },
  # { chars = "\u00026", key = "Key6", mods = "Command" },
  # { chars = "\u00027", key = "Key7", mods = "Command" },
  # { chars = "\u00028", key = "Key8", mods = "Command" },
  # { chars = "\u00029", key = "Key9", mods = "Command" },
  # { action = "CreateNewTab", key = "A", mods = "Command" },

  # { chars = "\u0000", key = "Space", mods = "Control" },

  { chars = "\u001B[59;5u", key = "Semicolon", mods = "Control" },
  { chars = "\u001B[45;5u", key = "Minus", mods = "Control" },
  { key = "Comma", mods = "Command", command = { args = [
    "-c",
    "open ~/.config/alacritty/alacritty.yml",
  ], program = "sh" } },
  # { key = "T", mods = "Command | Shift", action = "CreateNewTab" },
]
