#!/bin/sh

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
  export PATH=/Users/lijialin/.local/bin:$PATH
  export PATH=/Users/lijialin/.cargo/bin:$PATH
  export PATH=/opt/homebrew/bin:$PATH
  export PATH="/opt/homebrew/sbin:$PATH"
  export PATH="/opt/homebrew/opt/curl/bin:$PATH"
	;;

Linux)
	export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac


# HISTFILE="$XDG_DATA_HOME"/zsh/history
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.local/share/neovim/bin":$PATH
eval "$(fnm env --use-on-cd)"
eval "$(zoxide init zsh)"
# eval "$(starship init zsh)"
