#!/bin/sh

# ---- system -----------------------------------------
case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
  export PATH=/Users/lijialin/.local/bin:$PATH
  export PATH=/Users/lijialin/.cargo/bin:$PATH
  export PATH=/opt/homebrew/bin:$PATH
  export PATH="/opt/homebrew/sbin:$PATH"
  export PATH="/opt/homebrew/opt/curl/bin:$PATH"
  export PATH="/Users/lijialin/Library/Rime/plum:$PATH"
  export PATH=/opt/local/bin:$PATH
  export PATH=/opt/local/sbin:$PATH
  export N_PREFIX=$HOME/.n
  export PATH=$N_PREFIX/bin:$PATH
  # export VOLTA_FEATURE_PNPM=1
  # export PATH="/opt/homebrew/opt/sqlite/bin:$PATH"
  # export PNPM_HOME="/Users/lijialin/.config/pnpm"
  # case ":$PATH:" in
  #   *":$PNPM_HOME:"*) ;;
  #   *) export PATH="$PNPM_HOME:$PATH" ;;
  # esac
	;;

Linux)
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac


# export LC_ALL=C
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.local/share/neovim/bin":$PATH
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
