#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="alacritty"
export BROWSER="chrome"
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.local/share/neovim/bin":$PATH
#export PATH="$PATH:./node_modules/.bin"
# eval "$(fnm env)"
eval "$(fnm env --use-on-cd)"
eval "$(zoxide init zsh)"
# eval "$(starship init zsh)"
# eval "`pip completion --zsh`"

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
  export PATH=/Users/lijialin/.local/bin:$PATH
  export PATH=/Users/lijialin/.cargo/bin:$PATH
  export PATH=/opt/homebrew/bin:$PATH
  export PATH="/opt/homebrew/sbin:$PATH"
  export PATH="/opt/homebrew/opt/curl/bin:$PATH"
	;;

Linux)
	# alias ls='ls --color=auto'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac
