#!/bin/sh

export PATH=/Users/lijialin/.local/bin:$PATH
export PATH=/Users/lijialin/.cargo/bin:$PATH
export PATH=/opt/homebrew/bin:$PATH
export PATH="/opt/homebrew/sbin:$PATH"
export PATH="/opt/homebrew/opt/curl/bin:$PATH"
export PATH="/Users/lijialin/Library/Rime/plum:$PATH"
export PATH=/opt/local/bin:$PATH
export PATH=/opt/local/sbin:$PATH
export N_PREFIX=$HOME/.n
export PATH=$N_PREFIX/bin:$PATH
export PNPM_HOME="/Users/lijialin/Library/pnpm"

if [ -d "/opt/homebrew/opt/ruby/bin" ]; then
  export PATH=/opt/homebrew/opt/ruby/bin:$PATH
  export PATH=`gem environment gemdir`/bin:$PATH
fi
