#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

GAP=10
grid=24:24:2:2:20:20
BAR_HEIGHT=$(sketchybar -m --query bar | jq -r '.height')

# global settings
yabai -m config layout bsp
yabai -m config window_zoom_persist off
yabai -m config auto_balance off

yabai -m config mouse_modifier fn
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow off

# general space settings
yabai -m config external_bar all:"${BAR_HEIGHT}":0
yabai -m config top_padding "$GAP"
yabai -m config bottom_padding "$GAP"
yabai -m config left_padding "$GAP"
yabai -m config right_padding "$GAP"
yabai -m config window_gap "$GAP"

yabai -m config --space 2 layout stack
yabai -m config --space 3 layout stack
yabai -m config --space 4 layout float

# Refocus windows with window is closed or app destroyed
# yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# rule
yabai -m rule --add app="^(企业微信|QQ|微信|网易云音乐|喜马拉雅|QQ音乐|Listen1|Spotify|音乐|mpv|IINA)" space=4 grid=$grid
yabai -m rule --add app="^(微信开发者工具)" space=3
yabai -m rule --add app="^(Code)" space=2
yabai -m rule --add app="^(CLion|PyCharm|IntelliJ IDEA|WebStorm-EAP|WebStorm|网易邮箱大师)" manage=off
yabai -m rule --add app="^(SnailSVN|pot|预览|系统设置|mpv|访达|网易邮箱大师|LiberOffice)" manage=off grid=$grid
yabai -m rule --add app="^(Calculator|System Preferences|Archive Utility)$" manage=off

yabai -m rule --add app=".*" sub-layer=normal
# yabai -m rule --add app="^通知.*$" sticky=on layer=above

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"

echo "yabai configuration loaded.."
