#!/usr/bin/env bash

# ██╗   ██╗       █████╗       ██████╗        █████╗       ██╗
# ╚██╗ ██╔╝      ██╔══██╗      ██╔══██╗      ██╔══██╗      ██║
#  ╚████╔╝       ███████║      ██████╔╝      ███████║      ██║
#   ╚██╔╝        ██╔══██║      ██╔══██╗      ██╔══██║      ██║
#    ██║         ██║  ██║      ██████╔╝      ██║  ██║      ██║
#    ╚═╝         ╚═╝  ╚═╝      ╚═════╝       ╚═╝  ╚═╝      ╚═╝

# for this to work you must configure sudo such that
# it will be able to run the command without password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# .. more yabai startup stuff

GAP=10
grid=24:24:2:2:20:20
BAR_HEIGHT=$(sketchybar -m --query bar | jq -r '.height')

# global settings
yabai -m config external_bar all:"${BAR_HEIGHT}":0
yabai -m config mouse_modifier super
yabai -m config window_zoom_persist on
yabai -m config auto_balance off

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_placement second_child
yaml -m config window_topmost off
yabai -m config window_shadow off

# general space settings
yabai -m config layout bsp
yabai -m config top_padding "$GAP"
yabai -m config bottom_padding "$GAP"
yabai -m config left_padding "$GAP"
yabai -m config right_padding "$GAP"
yabai -m config window_gap "$GAP"

# SPACE LABELS
LABELS=(
	info
	code
	preview
	comms
	other
)

for ((i = 1; i <= "${#LABELS[@]}"; i++)); do
	yabai -m space "${i}" --label "${LABELS[(($i - 1))]}"
done

yabai -m config --space code layout stack
yabai -m config --space preview layout stack
yabai -m config --space comms layout float

# Refocus windows with window is closed or app destroyed
# yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# rule
yabai -m rule --add app="^(企业微信|QQ|微信|网易云音乐|喜马拉雅|QQ音乐|Listen1|Spotify|音乐|mpv|IINA)" space=comms grid=$grid
yabai -m rule --add app="^(微信开发者工具)" space=preview
yabai -m rule --add app="^(Code)" space=code
yabai -m rule --add app="^(CLion|PyCharm|IntelliJ IDEA|WebStorm-EAP|WebStorm|网易邮箱大师)" manage=off
yabai -m rule --add app="^(SnailSVN|pot|预览|系统设置|mpv|访达|网易邮箱大师|LiberOffice)" manage=off grid=$grid
yabai -m rule --add app="^(Calculator|System Preferences|Archive Utility)$" manage=off

yabai -m rule --add app=".*" layer=normal
yabai -m rule --add app="^通知.*$" sticky=on layer=above

yabai -m space --balance

echo "yabai configuration loaded.."

# alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA`~-_=+\|]}[{;:'",<.>/?
